<a href="https://colab.research.google.com/github/ldthinh220802/sharksthinh/blob/main/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [5]:
import numpy as np
np.arange(-15,27,0.7)


array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [7]:
np.random.normal(loc = 2.7, scale = 1.2, size = 40)

array([ 4.81686282,  3.18018865,  3.87448558,  5.38907184,  4.94106959,
        1.52726654,  3.8401061 ,  2.51837135,  2.57613738,  3.1927182 ,
        2.87285229,  4.44512821,  3.61324527,  2.84601002,  3.23263588,
        3.10040919,  4.49289489,  2.45381008,  3.07568124,  1.67508511,
       -0.36358778,  3.48434231,  3.73732344,  1.80940198,  5.42370555,
        0.95476119,  2.75491022,  2.47537938,  4.53933506,  4.46323052,
        2.88593691,  3.15379502,  1.6346571 ,  0.32304424,  2.28250542,
        2.88761876,  4.17634882,  4.14285582,  2.23520782,  2.3372367 ])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [9]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)

array(['Viet Nam', 'Britain', 'Britain', 'Russia', 'Viet Nam', 'Viet Nam',
       'Britain', 'France', 'Singapore', 'France', 'Viet Nam', 'Russia',
       'France', 'France', 'Viet Nam', 'Britain', 'Viet Nam'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [24]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 9,[0.4, 0.2, 0.1, 0.1, 0,2])

array(['Viet Nam', 'Viet Nam', 'Britain', 'Britain', 'Viet Nam', 'Russia',
       'Viet Nam', 'Russia', 'Viet Nam'], dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [27]:
from scipy import stats
stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([15.01336121,  9.69366818, 13.73276523, 14.19980402, 12.85600024,
       14.03586399, 10.99133972, 10.92945439, 13.62240113,  8.97119858,
       13.9265328 , 12.57508452, 11.19034036, 13.35724167, 12.65076271,
       10.90422405, 14.77938028, 18.45676711, 13.84106568, 14.35947523,
       17.9411876 , 12.06650285, 16.6879727 , 14.6883506 ,  6.31263454,
        8.27051335, 13.79239799, 11.92481241, 13.38536569, 14.6012914 ])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [30]:
stats.poisson.rvs(loc=100,
                              mu=50,
                              size=100)

array([153, 151, 141, 144, 146, 148, 137, 148, 147, 159, 152, 153, 151,
       143, 139, 148, 152, 152, 142, 146, 158, 148, 155, 148, 153, 153,
       148, 136, 144, 156, 155, 143, 151, 138, 144, 148, 149, 164, 152,
       163, 144, 154, 152, 149, 153, 154, 138, 138, 152, 155, 141, 136,
       147, 152, 142, 155, 159, 138, 156, 149, 154, 152, 151, 154, 142,
       158, 141, 144, 154, 149, 144, 153, 147, 152, 143, 145, 177, 143,
       147, 154, 133, 150, 138, 163, 146, 154, 145, 143, 164, 155, 155,
       138, 155, 151, 151, 134, 152, 155, 153, 155])