<a href="https://colab.research.google.com/github/ldthinh220802/sharksthinh/blob/main/to%C3%A1n_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
def  matran(n):
     rd = np.random.randint(0,10,(n,n))
     print('ma tran',rd)
     dinhthuc = np.linalg.det(rd)
     rankA = np.linalg.matrix_rank(rd)
     print('dinh thuc',dinhthuc)
     print('rank',rankA)
     hai =rd**2
     ba = rd**3
     print('a^2',hai)
     print('a^3',ba)
     return rd , dinhthuc , rankA , hai , ba
n = int(input('ma tran cap '))
matran(n)     

ma tran cap 3
ma tran [[5 3 1]
 [5 2 1]
 [7 9 5]]
dinh thuc -17.999999999999996
rank 3
a^2 [[25  9  1]
 [25  4  1]
 [49 81 25]]
a^3 [[125  27   1]
 [125   8   1]
 [343 729 125]]


(array([[5, 3, 1],
        [5, 2, 1],
        [7, 9, 5]]), -17.999999999999996, 3, array([[25,  9,  1],
        [25,  4,  1],
        [49, 81, 25]]), array([[125,  27,   1],
        [125,   8,   1],
        [343, 729, 125]]))